### ISSUE TITLE
最近java和node版的小助手全部都失效了？

### ISSUE THREAD

**Issue by UselessGM** [kb1000fx/NodeOmenHelper#1]
如题，Node版本的小助手问题是闪退.....在输入密码后一会就闪退掉了，不知道怎么回事

**Comment by kb1000fx** [comment]
把config.json里的ignoreError改成false就能输出报错信息了，我这显示号被封了，应该是hp开始查了

**Comment by UselessGM** [comment]
哦哦，看到了，谢谢大佬
另外除了号封掉以外还有个报错
TypeError: Cannot read property 'state' of undefined
    at C:\Users\Administrator\OneDrive\桌面\NodeOmenHelper-main\dist\lib\Challenge.js:57:39
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
大佬能帮忙看看嘛

**Comment by kb1000fx** [comment]
> 哦哦，看到了，谢谢大佬
> 另外除了号封掉以外还有个报错
> TypeError: Cannot read property 'state' of undefined
> at C:\Users\Administrator\OneDrive\桌面\NodeOmenHelper-main\dist\lib\Challenge.js:57:39
> at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 大佬能帮忙看看嘛

这个错误是因为获取到的结果里面数组result是空的，我试了几次都是第一个任务成功之后做第二个任务时出现这个错误，可能是hp限制了请求的频率。这个项目应该不会继续更新了，还有omen抽奖需求的话可以尝试手动挂任务，或者问问其他工具的作者。

**Comment by UselessGM** [comment]
> > 哦哦，看到了，谢谢大佬
> > 另外除了号封掉以外还有个报错
> > TypeError: Cannot read property 'state' of undefined
> > at C:\Users\Administrator\OneDrive\桌面\NodeOmenHelper-main\dist\lib\Challenge.js:57:39
> > at processTicksAndRejections (node:internal/process/task_queues:96:5)
> > 大佬能帮忙看看嘛
> 
> 这个错误是因为获取到的结果里面数组result是空的，我试了几次都是第一个任务成功之后做第二个任务时出现这个错误，可能是hp限制了请求的频率。这个项目应该不会继续更新了，还有omen抽奖需求的话可以尝试手动挂任务，或者问问其他工具的作者。

好的，麻烦您了，谢谢大佬
